// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjrncku4ZNcUyNloLLq1MyDn6LFuzCW5Q',
    appId: '1:1019328572822:web:44d485173dfa820ba781b7',
    messagingSenderId: '1019328572822',
    projectId: 'rk-kitchen-16996',
    authDomain: 'rk-kitchen-16996.firebaseapp.com',
    databaseURL: 'https://rk-kitchen-16996-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rk-kitchen-16996.firebasestorage.app',
    measurementId: 'G-6H20Q3LQJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXBBwBgtavqkP0b3EyARcqxq4M5YktOg',
    appId: '1:1019328572822:android:858ed73dd5c29c05a781b7',
    messagingSenderId: '1019328572822',
    projectId: 'rk-kitchen-16996',
    databaseURL: 'https://rk-kitchen-16996-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rk-kitchen-16996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIoA_B8a3hNpt_qs_OJNwUx4fSQfkzmM',
    appId: '1:1019328572822:ios:376147403cd8a2d4a781b7',
    messagingSenderId: '1019328572822',
    projectId: 'rk-kitchen-16996',
    databaseURL: 'https://rk-kitchen-16996-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rk-kitchen-16996.firebasestorage.app',
    iosBundleId: 'com.example.rkKitchenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIoA_B8a3hNpt_qs_OJNwUx4fSQfkzmM',
    appId: '1:1019328572822:ios:376147403cd8a2d4a781b7',
    messagingSenderId: '1019328572822',
    projectId: 'rk-kitchen-16996',
    databaseURL: 'https://rk-kitchen-16996-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rk-kitchen-16996.firebasestorage.app',
    iosBundleId: 'com.example.rkKitchenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjrncku4ZNcUyNloLLq1MyDn6LFuzCW5Q',
    appId: '1:1019328572822:web:b4a3f37837a988dfa781b7',
    messagingSenderId: '1019328572822',
    projectId: 'rk-kitchen-16996',
    authDomain: 'rk-kitchen-16996.firebaseapp.com',
    databaseURL: 'https://rk-kitchen-16996-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rk-kitchen-16996.firebasestorage.app',
    measurementId: 'G-T8NER78PKL',
  );
}
